services:

  postgres:
    image: postgres:16-alpine
    container_name: restaurant-postgres
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant -d restaurant"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: restaurant-redis
    networks:
      - restaurant-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: restaurant-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: restaurant
      RABBITMQ_DEFAULT_PASS: restaurant
    ports:
      - "15672:15672"       # UI доступен с хоста
    networks:
      - restaurant-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: restaurant-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - restaurant-net

  grafana:
    image: grafana/grafana:latest
    container_name: restaurant-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - restaurant-net
    depends_on:
      - prometheus

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant
      SPRING_DATASOURCE_USERNAME: restaurant
      SPRING_DATASOURCE_PASSWORD: restaurant
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - restaurant-net

  frontend:
    image: nginx:alpine
    container_name: restaurant-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - restaurant-net

  nginx:
    image: nginx:alpine
    container_name: restaurant-nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - restaurant-net

volumes:
  postgres_data:

networks:
  restaurant-net:
    driver: bridge

